# Generated by Django 5.2.7 on 2025-11-30 13:53

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username must consist of @ followed by at least three alphanumericals",
                                regex="^@\\w{3,}$",
                            )
                        ],
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "preferred_spiciness",
                    models.FloatField(
                        default=1.5, help_text="The user's preferred spiciness level"
                    ),
                ),
                (
                    "preferred_cuisine",
                    models.FloatField(
                        blank=True,
                        help_text="The user's preferred cuisine id",
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A description of the recipe."
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")],
                        default=1,
                        help_text="Estimated difficulty of the recipe",
                    ),
                ),
                (
                    "spiciness",
                    models.IntegerField(
                        choices=[
                            (0, "Not Spicy"),
                            (1, "Mild"),
                            (2, "Medium"),
                            (3, "Hot"),
                            (4, "Very Hot"),
                            (5, "ULTRA Hot"),
                        ],
                        default=0,
                        help_text="The spiciness level of the recipe",
                    ),
                ),
                (
                    "cuisine",
                    models.IntegerField(
                        choices=[
                            (1, "World 🗺️"),
                            (2, "British 🇬🇧"),
                            (3, "French 🇫🇷"),
                            (4, "Italian 🇮🇹"),
                            (5, "Mexican 🇲🇽"),
                            (6, "Spanish 🇪🇸"),
                            (7, "Chinese 🇨🇳"),
                            (8, "Japanese 🇯🇵"),
                            (9, "Korean 🇰🇷"),
                            (10, "Indian 🇮🇳"),
                            (11, "Thai 🇹🇭"),
                            (12, "Vietnamese 🇻🇳"),
                            (13, "Eastern European 🍲"),
                            (14, "African 🌍"),
                            (15, "Carribbean 🍍"),
                            (16, "American 🍔"),
                            (17, "German 🇩🇪"),
                            (18, "Greek 🇬🇷"),
                            (19, "Middle Eastern 🍛"),
                            (20, "Turkish 🇹🇷"),
                            (21, "Caucasian 🏔️"),
                            (22, "South American 💃"),
                        ],
                        default=1,
                        help_text="The cuisine of the recipe",
                    ),
                ),
                (
                    "vegetarian",
                    models.BooleanField(
                        default=False, help_text="Whether the recipe is vegetarian"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="An optional image for the recipe",
                        null=True,
                        upload_to="recipe/images",
                    ),
                ),
                (
                    "time",
                    models.IntegerField(
                        default=30,
                        help_text="Time taken to complete the recipe (in minutes)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(help_text="The step number of the instruction"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The text of the instruction", max_length=500
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="An optional image for this instruction step",
                        null=True,
                        upload_to="recipe/instructions",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructions",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "step")},
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the ingredient", max_length=100
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True,
                        help_text="The quantity of the ingredient",
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="The unit of measurement", max_length=50
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("recipe", "name")},
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Share your thoughts about this recipe",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="recipes.comment",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipe", "-created_at"],
                        name="recipes_com_recipe__d91579_idx",
                    ),
                    models.Index(
                        fields=["recipe", "author"],
                        name="recipes_com_recipe__8c1cb9_idx",
                    ),
                    models.Index(
                        fields=["parent_comment"], name="recipes_com_parent__8c9fc2_idx"
                    ),
                ],
            },
        ),
    ]
