# Generated by Django 5.2.7 on 2025-12-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="visibility",
            field=models.IntegerField(
                choices=[(0, "Public"), (1, "Private")],
                default=0,
                help_text="Visibility of the recipe",
            ),
        ),
    ]
