# Generated by Django 5.2.7 on 2025-11-28 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Summary or notes about why this recipe is being reported",
                        max_length=1000,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the report was created"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="The recipe being reported",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="The user who made the report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipe", "-created_at"],
                        name="recipes_rep_recipe__c4e961_idx",
                    ),
                    models.Index(
                        fields=["reporter", "-created_at"],
                        name="recipes_rep_reporte_256324_idx",
                    ),
                ],
            },
        ),
    ]
