# Generated by Django 5.2.7 on 2025-12-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_add_servings_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recipes_favourited_num",
            field=models.IntegerField(default=0),
        ),
    ]
