# Generated by Django 5.2.7 on 2025-11-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_ingredients_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(
                        help_text="The step number of the instruction", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The text of the instruction", max_length=500
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "step")},
            },
        ),
    ]
