# Generated by Django 5.2.7 on 2025-11-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_instruction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="step",
            field=models.IntegerField(help_text="The step number of the instruction"),
        ),
    ]
