# Generated by Django 5.2.7 on 2025-11-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_remove_recipe_instructions_recipe_image_recipe_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instructions",
                to="recipes.recipe",
            ),
        ),
    ]
