# Generated by Django 5.2.7 on 2025-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_instruction_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruction",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An optional image for this instruction step",
                null=True,
                upload_to="recipe/instructions",
            ),
        ),
    ]
